---
providers:
  domeneshop:
    class: octodns_domeneshop.DomeneshopProvider
    token: env/DOMENESHOP_TOKEN
    secret: env/DOMENESHOP_SECRET
    include_nameservers: true

  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    enforce_order: false

zones:
  # Dynamic zone discovery - '*' will fetch all zones from the provider
  '*':
    sources:
      - yaml
    targets:
      - domeneshop

